// Generated by CoffeeScript 1.4.0
/**
* DeftJS Application class for the Duvi application.
*/

Ext.define("Duvi.Application", {
  extend: "Deft.mvc.Application",
  requires: ["Duvi.config.AppConfig", "Duvi.view.Viewport"],
  /**
  * init() runs when Ext.onReady() is called.
  */

  init: function() {
    this.beforeInit();
    Deft.Injector.configure(this.buildInjectorConfiguration());
    return this.afterInit();
  },
  /**
  * @protected
  * Returns the configuration object to pass to Deft.Injector.configure(). Override in subclasses to alter the Injector configuration before returning the config object.
  * @return {Object} The Injector configuration object.
  */

  buildInjectorConfiguration: function() {
    var config;
    config = {
      appConfig: {
        className: "Duvi.config.AppConfig",
        parameters: [
          {
            environment: Duvi.config.AppConfig.MOCK_DATA_ENV
          }
        ]
      }
    };
    return config;
  },
  /**
  * @protected
  * Runs at the start of the init() method. Override in subclasses if needed.
  */

  beforeInit: function() {},
  /**
  * @protected
  * Runs at the end of the init() method. Useful to create initial Viewport, start Jasmine tests, etc.
  */

  afterInit: function() {
    Ext.tip.QuickTipManager.init();
    return Ext.create("Duvi.view.Viewport");
  }
});
