/*
 * Copyright (C) 2014 Jorge S. (duvi-framework@jsan.eu)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by CoffeeScript 1.4.0
/**
* Main (root) UI container.
*/

Ext.define("Duvi.view.MainPanel", {
  extend: "Ext.panel.Panel",
  alias: "widget.duvi-view-mainPanel",
  controller: "Duvi.controller.MainPanelController",
  header: true,
  title: "Main Panel",
  layout: "anchor",
  defaults: {
    anchor: "100% 100%"
  },
  initComponent: function() {
    Ext.applyIf(this, {
      items: [
        {
          html: "<div style='padding: 20px; font-size: x-large'>Add your own views as children of MainPanel.</span>"
        }
      ]
    });
    return this.callParent(arguments);
  }
});
