// Generated by CoffeeScript 1.4.0
/**
* Viewport shell for the Duvi application.
*/

Ext.define("Duvi.view.Viewport", {
  extend: "Ext.container.Viewport",
  requires: ["Duvi.view.MainPanel"],
  layout: {
    type: "fit"
  },
  initComponent: function() {
    Ext.applyIf(this, {
      items: [
        {
          xtype: "duvi-view-mainPanel"
        }
      ]
    });
    return this.callParent(arguments);
  }
});
