/*
 * Copyright (C) 2014 Jorge S. (duvi-framework@jsan.eu)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by CoffeeScript 1.4.0
/**
* Viewport shell for the Duvi application.
*/

Ext.define("Duvi.view.Viewport", {
  extend: "Ext.container.Viewport",
  requires: ["Duvi.view.MainPanel"],
  layout: {
    type: "fit"
  },
  initComponent: function() {
    Ext.applyIf(this, {
      items: [
        {
          xtype: "duvi-view-mainPanel"
        }
      ]
    });
    return this.callParent(arguments);
  }
});
